//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloak.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloak.Http.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media format can read type {0}.
        /// </summary>
        internal static string NoMediaFormatCanReadType {
            get {
                return ResourceManager.GetString("NoMediaFormatCanReadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media format can write type {0}.
        /// </summary>
        internal static string NoMediaFormatCanWriteType {
            get {
                return ResourceManager.GetString("NoMediaFormatCanWriteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is an invalid JSON token.
        /// </summary>
        internal static string StreamIsInvalidJsonToken {
            get {
                return ResourceManager.GetString("StreamIsInvalidJsonToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is an invalid XML document.
        /// </summary>
        internal static string StreamIsInvalidXmlDocument {
            get {
                return ResourceManager.GetString("StreamIsInvalidXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read content as any of the specified types: {0}, {1}, {2}, {3}.
        /// </summary>
        internal static string UnableToReadContentFourTypes {
            get {
                return ResourceManager.GetString("UnableToReadContentFourTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read content as any of the specified types: {0}, {1}, {2}.
        /// </summary>
        internal static string UnableToReadContentThreeTypes {
            get {
                return ResourceManager.GetString("UnableToReadContentThreeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read content as any of the specified types: {0}, {1}.
        /// </summary>
        internal static string UnableToReadContentTwoTypes {
            get {
                return ResourceManager.GetString("UnableToReadContentTwoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read media of type {0}.
        /// </summary>
        internal static string UnableToReadMedia {
            get {
                return ResourceManager.GetString("UnableToReadMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read media of type {0} negotiated from media type &quot;{1}&quot;.
        /// </summary>
        internal static string UnableToReadMediaNegotiatedFrom {
            get {
                return ResourceManager.GetString("UnableToReadMediaNegotiatedFrom", resourceCulture);
            }
        }
    }
}
