//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloak {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloak.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}[{1}].
        /// </summary>
        internal static string ElementIndexedPath {
            get {
                return ResourceManager.GetString("ElementIndexedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}.
        /// </summary>
        internal static string ElementNonIndexedPath {
            get {
                return ResourceManager.GetString("ElementNonIndexedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        internal static string ExpandedName {
            get {
                return ResourceManager.GetString("ExpandedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect attribute name &apos;{0}&apos; at &apos;{1}&apos;.
        /// </summary>
        internal static string ExpectedAttributeName {
            get {
                return ResourceManager.GetString("ExpectedAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected child element &apos;{0}&apos; at &apos;{1}&apos;.
        /// </summary>
        internal static string ExpectedChildElement {
            get {
                return ResourceManager.GetString("ExpectedChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect element name &apos;{0}&apos; at &apos;{1}&apos;.
        /// </summary>
        internal static string ExpectedElementName {
            get {
                return ResourceManager.GetString("ExpectedElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-empty attribute &apos;{0}&apos; at &apos;{1}&apos;.
        /// </summary>
        internal static string ExpectedNonEmptyAttribute {
            get {
                return ResourceManager.GetString("ExpectedNonEmptyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not call a method: {0}.
        /// </summary>
        internal static string ExpressionDoesNotCallMethodFormat {
            get {
                return ResourceManager.GetString("ExpressionDoesNotCallMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not select a member: {0}.
        /// </summary>
        internal static string ExpressionDoesNotSelectMemberFormat {
            get {
                return ResourceManager.GetString("ExpressionDoesNotSelectMemberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression body must be a {0}: {1}.
        /// </summary>
        internal static string InvalidLambdaExpressionBody {
            get {
                return ResourceManager.GetString("InvalidLambdaExpressionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}@{1}.
        /// </summary>
        internal static string QualifiedAttributePath {
            get {
                return ResourceManager.GetString("QualifiedAttributePath", resourceCulture);
            }
        }
    }
}
